# Action to clean the Submitty Slack for Travis-CI messages in #travis-ci, once
# a day at midnight.

name: Delete Travis-CI Slack Messages

on:
  #push:
  #  branches: [ master ]

  schedule:
    - cron: "0 0 * * *"

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run cleaner
      run: python3 clean_slack.py "${{ secrets.SLACK_TOKEN }}" "travis-ci"
